### ISSUE TITLE
Allow saving whole transform code if it was created in another module

### ISSUE THREAD

**Issue by wuhu** [lf1-io/padl#160]
If I get a transform from another module and do

```python
from othermodule import MyTransform
x = MyTransform()
```

saving will save just that - it will not get the code defining the transform.

Sometimes it could be desirable to save the code defining the Transform instead.

We should somehow enable that.

Different ways come into mind:
1. make it possible to set a flag in the decorator

```python
@transform(saveall=True)
class MyTransform:
    ...   
```

2. add a function that modifies the way the transform saves

```python
from othermodule import MyTransform
x = MyTransform()
x = saveall(x)
```

3. add a function that modifies the way a whole package / module saves

```python
import othermodule
saveall(othermodule)
```

**Comment by blythed** [comment]
For example in `tatenen` models should be saved with reference to `tatenen` codebase.

**Comment by wuhu** [comment]
https://github.com/lf1-io/padl/pull/288

**Comment by sjrl** [comment]
@wuhu Can this issue be closed now?
