### ISSUE TITLE
Investigate support for earlier python versions

### ISSUE THREAD

**Issue by blythed** [lf1-io/padl#189]
Would be nice to go back to python 3.7 due to collab support.

**Comment by wuhu** [comment]
The saver relies on `ast.get_source_segment`, `AST.end_lineno` and `AST.end_col_offset`. There were added in python 3.8.

It doesn't look like there's a straight forward way to do without those.

**Comment by sjrl** [comment]
We've decide to come back to this. PR #315 addresses python 3.7 compatibility.

**Comment by sjrl** [comment]
PR #315 has been merged.
