### ISSUE TITLE
read README and give Duncan feedback.

### ISSUE THREAD

**Issue by blythed** [lf1-io/padl#191]

**Comment by sjrl** [comment]
The example `to_integer` does not currently work https://github.com/lf1-io/padl/blob/5b37997b6f79275a4aef8f97cbb7f74a15f6b05f/README.md?plain=1#L96-L108. 

- The initialization passes too many arguments
- The token `<unk>` doesn't have an entry in `self.dictionary`

**Comment by sjrl** [comment]
Define `EOS_VALUE` for the `to_tensor` example to work https://github.com/lf1-io/padl/blob/5b37997b6f79275a4aef8f97cbb7f74a15f6b05f/README.md?plain=1#L90

**Comment by sjrl** [comment]
Change `this.lower_case()` to `this.lower()` https://github.com/lf1-io/padl/blob/5b37997b6f79275a4aef8f97cbb7f74a15f6b05f/README.md?plain=1#L121
