### ISSUE TITLE
Allow serializer and deserializer to be passed to value.

### ISSUE THREAD

**Issue by blythed** [lf1-io/padl#194]
We could then save these functions using the serializer itself.

**Comment by wuhu** [comment]
This could work like this:

```python
def mysave(value, path):
    [... define how to save *value* at *path* ...]
 
def myload(path):
    [... define how to load from *path* ..., should return *value* ...]

[...]

a = value(x, serializer=(mysave, myload))
```

The serializer will call the save-function upon saving and put the load-function in the `transforms.py` then use it to load.
Therefore, we need to get the source of load-function (can be done with `inspect.getsource`).

Problem could be that there is no check that it will actually load. We could (should?) add a check - try loading when saving.

**Comment by wuhu** [comment]
done in #209 

Save function must look like this, takes the path, an integer "i" that can be used to construct a filename and must return a filename:

```
def mysave(val, path, i):
    filename = ...
    return filename
```

The load function takes a path and returns the value
```
def myload(path):
    return ...
```

These can then be used via

```
value(x, (mysave, myload))
```

**Comment by blythed** [comment]
Complex case:

```python
def mysave(val, path):
    return [f1, f2, ...]

def myload(output_of_mysave):
    return thing
```

**Comment by wuhu** [comment]
Adapted the PR according to Friday's discussion:

The save function now does not take the `i` - the `path` already has it.
Instead, one can pass a file suffix as the third element of the tuple.

```python
def mysave(val, path):
    [ do the saving, return nothing ]

def myload(path):
    return [ load from path ]

x = value(x, (mysave, myload, '_append.this')
```

The complex case (see previous comment) is also supported.
I've added a section to the docs explaining both.
