### ISSUE TITLE
add more detailed documentation

### ISSUE THREAD

**Issue by wuhu** [lf1-io/padl#205]
- [x] operators
- [x] stages
- [x] preprocess / forward / postprocess
- [x] this
- [x] serializers

**Comment by jasonkhadka** [comment]
also make the examples in doc work. 
`pytest --doctest-modules`  fails at the moment.

**Comment by sjrl** [comment]
> _if needed_ also make the examples in doc work. `pytest --doctest-modules` fails at the moment.

I've started going through the doctest examples to see if I can get them to pass in branch https://github.com/lf1-io/padl/tree/doc_tests

**Comment by blythed** [comment]
Examples for the frontpage website:

- Side-by-side preprocess/ dataloader old way vs. padl
- loading model old way and new way
- ...

**Comment by jasonkhadka** [comment]
building model old way 

```python
class SubNet1(torch.nn.Module):
    def forward(self, x):
          ...

class SubNet2(torch.nn.Module):
    def forward(self, x):
          ...

class SuperNet(torch.nn.Module):
    def __init__(self):
            self.subnet1 = SubNet1()
            self.subnet2 = SubNet2()
    def forward(self, x):
          x = self.subnet1(x)
          x = self.subnet2(x)
          return x
```

new way:


```python
@transform
class SubNet1(torch.nn.Module):
    def forward(self, x):
          ...

@transform
class SubNet2(torch.nn.Module):
    def forward(self, x):
          ...

SuperNet = (
     SubNet1
     >> SubNet2
)
```

**Comment by wuhu** [comment]
Hmm I think that's cheating a bit, you could just do

```python
SuperNet = torch.nn.Sequential(
    SubNet1(),
    SubNet2()
)
```
