### ISSUE TITLE
Bug in `padl/dumptools/inspector::cut' function

### ISSUE THREAD

**Issue by eramdiaz** [lf1-io/padl#206]
I get the following error when I add an `Unbatchify` in the following model:
```
mod = (to_tensor 
>> Batchify()
>> embedding
>> Unbatchify()
)
```
![Screenshot from 2021-11-04 11-18-36](https://user-images.githubusercontent.com/78182182/140296985-a13833c7-4ca7-492d-90d0-200dca379241.png)

If I don't add the `Unbatchify` everything works properly.

**Comment by wuhu** [comment]
This works
```
mod = (
    to_tensor 
    >> Batchify()
    >> embedding
    >> Unbatchify()
)```

this doesn't:

```
mod = (to_tensor 
    >> Batchify()
    >> embedding
    >> Unbatchify()
)
```

**Comment by eramdiaz** [comment]
Thanks Alex

**Comment by wuhu** [comment]
fixed
