### ISSUE TITLE
consider renaming certain functionality

### ISSUE THREAD

**Issue by blythed** [lf1-io/padl#235]
- [x] `stage -> mode`
- [x] `component -> stage`
- [x] `this -> same`

**Comment by sjrl** [comment]
Pytorch uses `mode` when referring to `eval` and `train`.

**Comment by sjrl** [comment]
> For `this`, we proposed `itself`, but it could be also `auto`, which is the greek prefix for `self`

I like `itself` over `auto`

**Comment by jasonkhadka** [comment]
`auto` has other meaning in other languages, example : https://en.cppreference.com/w/cpp/language/auto
Also it is most commonly understood as automatic than `self`. 
```
* stage -> mode
* component -> stage / division / component 
* this -> same
```

**Comment by wuhu** [comment]
Yes I like `stage -> mode`! I'm also in favor of `component -> stage`. In my head that was always the case. 'component' somehow confuses me.
I also like `this -> same`, agree that `auto` sounds a lot like automatic and could be confusing because of that.

**Comment by sjrl** [comment]
To clarify `this -> same` is a proposed name change to `same` or a proposal to leave the name as `this`? @wuhu @jasonkhadka

**Comment by wuhu** [comment]
the way I understood it the proposal is to call it "same"

**Comment by wuhu** [comment]
@sjrl @jasonkhadka @eramdiaz @blythed shall we have a vote, or are there any other suggestions?

**Comment by sjrl** [comment]
I think we are ready for a vote.

**Comment by jasonkhadka** [comment]
yeah, it was a proposal to change it to "same", to make it close to "self".
