### ISSUE TITLE
Print of self.finally in try

### ISSUE THREAD

**Issue by eramdiaz** [lf1-io/padl#239]
## 🐞 Bug

for some reason when the attribute `self.finally_transform` of `Try` is printed, `self.else_transform` is printed. This is not in main yet.

**Comment by wuhu** [comment]
@eramdiaz, when creating a bug report, make sure to delete the sections of the template you don't need or (even better) write something in there.

**Comment by eramdiaz** [comment]
I will do it that way, @wuhu . This issue is solved now.
