### ISSUE TITLE
Edge case in decorating a Module instance

### ISSUE THREAD

**Issue by blythed** [lf1-io/padl#243]
```python
from torchvision.models.densenet import DenseNet
from padl import transform


@transform
class ImageClassifier(DenseNet):
    def __init__(self):
        super(ImageClassifier, self).__init__(48, (6, 12, 36, 24), 96)

    def load_state_dict(self, state_dict, strict=True):
        # '.'s are no longer allowed in module names, but previous _DenseLayer
        # has keys 'norm.1', 'relu.1', 'conv.1', 'norm.2', 'relu.2', 'conv.2'.
        # They are also in the checkpoints in model_urls. This pattern is used
        # to find such keys.
        # Credit - https://github.com/pytorch/vision/blob/master/torchvision/models/densenet.py#def _load_state_dict()
        import re
        pattern = re.compile(r'^(.*denselayer\d+\.(?:norm|relu|conv))\.((?:[12])\.(?:weight|bias|running_mean|running_var))$')

        for key in list(state_dict.keys()):
            res = pattern.match(key)
            if res:
                new_key = res.group(1) + res.group(2)
                state_dict[new_key] = state_dict[key]
                del state_dict[key]

        return super(ImageClassifier, self).load_state_dict(state_dict, strict)
```

This breaks with message:

```
In [2]: layer
Out[2]: ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/lf1-io/padl/.venv/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/lf1-io/padl/.venv/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    389                             meth = cls._repr_pretty_
    390                             if callable(meth):
--> 391                                 return meth(obj, self, cycle)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):

~/lf1-io/padl/.venv/lib/python3.8/site-packages/padl/transforms.py in _repr_pretty_(self, p, cycle)
    399             title = make_bold(title)
    400         top_message = title + ':' + '\n\n'
--> 401         bottom_message = textwrap.indent(self._pd_longrepr(), '   ')
    402         p.text(top_message + bottom_message if not cycle else '...')
    403

~/lf1-io/padl/.venv/lib/python3.8/site-packages/padl/transforms.py in _pd_longrepr(self)
    956
    957     def _pd_longrepr(self) -> str:
--> 958         return torch.nn.Module.__repr__(self)
    959
    960

~/lf1-io/padl/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py in __repr__(self)
   1810             extra_lines = extra_repr.split('\n')
   1811         child_lines = []
-> 1812         for key, module in self._modules.items():
   1813             mod_str = repr(module)
   1814             mod_str = _addindent(mod_str, 2)

~/lf1-io/padl/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1175             if name in modules:
   1176                 return modules[name]
-> 1177         raise AttributeError("'{}' object has no attribute '{}'".format(
   1178             type(self).__name__, name))
   1179

AttributeError: 'ImageClassifier' object has no attribute '_modules'
```

The error doesn't occur with `t = transform(ImageClassifier())` with the decorator removed.

**Comment by wuhu** [comment]
I suspect that `DenseNet` does not work with `torch.nn.Module.__repr__`, perhaps we should use `super.__repr__` instead.

**Comment by wuhu** [comment]
That was not it.
Interestingly, it works when using
```python
    [...]
    super().__init__(...)
    [...]
```
instead of 
```python
    [...]
    super(ImageClassifier, self).__init__(...)
    [...]
    ```

**Comment by wuhu** [comment]
I've found the problem, still thinking about how to solve it:

When wrapping a class, we create a new class that inherits from the original class and `TorchModuleTransform`.

Thus, unwrapped, `ImageClassifier` inherits from `DenseNet`.
Wrapped, `ImageClassifier` inherits from `TorchModuleTransform` and the old `ImageClassifier` (thus indirecly from `DenseNet`).

`super().__init__(...)` calls `DenseNet.__init__(...)` in both cases as `super` auto-determines the class of the method from which it's being called.

The old `super(ImageClassifier, self).__init__(...)` calls the `__init__` of whatever is the first super class of `ImageClassifier`. Because `ImageClassifier` is the new `ImageClassifier`, that is `TorchModuleTransform`.

Thus, `TorchModuleTransform.__init__` is called when it should be `DenseNet.__init__` and a bunch of attributes don't get created (`_modules`, among others). When printing, `Module.__repr__` tries to access `_module` and fails.

**Comment by wuhu** [comment]
Simplest fix would be to require using `super()`. We could test for this and raise an Exception accordingly.
- This wouldn't be a problem for 3rd party modules as this happens only when using `transform` as a decorator.
- as far as I know `super(Class, self)...` isn't recommended anymore since `super()...` does the same and is shorter etc

Still, of course, for people who still use the old way it's one more thing to look up.

**Comment by sjrl** [comment]
> I've found the problem, still thinking about how to solve it:
> 
> When wrapping a class, we create a new class that inherits from the original class and `TorchModuleTransform`.
> 
> Unwrapped, `ImageClassifier` inherits from `DenseNet`. Wrapped, `ImageClassifier` inherits from `TorchModuleTransform` and the old `ImageClassifier` (thus indirecly from `DenseNet`).
> 
> `super().__init__(...)` calls `DenseNet.__init__(...)` in both cases as `super` auto-determines the class of the method from which it's being called. This is what we want.
> 
> The old `super(ImageClassifier, self).__init__(...)` calls the `__init__` of whatever is the first super class of `ImageClassifier`. Because `ImageClassifier` is the new `ImageClassifier`, that is `TorchModuleTransform`.
> 
> Thus, `TorchModuleTransform.__init__` is called when it should be `DenseNet.__init__` and a bunch of attributes don't get created (`_modules`, among others). When printing, `Module.__repr__` tries to access `_module` and fails.

Thanks for the investigation into this! In this specific case would the situation be fixed if we could change the order of the `super` classes in the new `ImageClassifier`? 
So basically change
```python
cls = type(cls.__name__, (trans_class, cls), {})
```
to 
```python
cls = type(cls.__name__, (cls, trans_class), {})
```

**Comment by blythed** [comment]
Same would also be true for the other statement. `return super(ImageClassifier, self).load_state_dict(state_dict, strict)`

**Comment by wuhu** [comment]
@blythed what do you think, should we require using "super" and close this for now?

**Comment by blythed** [comment]
yes
