### ISSUE TITLE
Release note on padl

### ISSUE THREAD

**Issue by eramdiaz** [lf1-io/padl#255]
## Description
It could be something nice for the community to include a release note when the `padl` version is upgraded. Something like: In the padl version z.z.zz the following features were developed:
1. feature_one
2. feature_two
3. feature_three

the following issues were solved:
1. issue_one 
2. issue_two
3. issue_three

Also, we might describe future directions or work.

**Comment by jasonkhadka** [comment]
Some release note examples that can be used:
* As given on wikipedia: https://en.wikipedia.org/wiki/Release_notes#Format_style
* pytorch : https://github.com/pytorch/pytorch/releases
* pandas: https://pandas.pydata.org/docs/whatsnew/v1.3.4.html

**Comment by wuhu** [comment]
- for now: create a simple list of changes at the end of each "phase"
- use the github "releases" feature
