### ISSUE TITLE
Kaggle data has been updated, MNIST notebook does not work as expected anymore. 

### ISSUE THREAD

**Issue by jasonkhadka** [lf1-io/padl#257]
Kaggle has updated MNIST dataset, so the notebook needs some modification to run. 
To prevent this in future, it might be better to either keep the data stored in the repo or use a stable version of data.

**Comment by sjrl** [comment]
We could also store a small subset of the data in the repo for demonstration purpose.

**Comment by jasonkhadka** [comment]
yes, we could do that but the training might not be effective with small dataset.
