### ISSUE TITLE
Method to apply preprocess+forward without postprocess

### ISSUE THREAD

**Issue by eramdiaz** [lf1-io/padl#28]
The `trans` part of an `lf` Transform will be now called `preprocess`. We consider this a convenient change since it is clear and gives an inmediate idea of its task. However, we have to give another name to the `trans` + `forward` part. Ideas?

**Comment by wuhu** [comment]
We just don't have that for the moment. Closing.

**Comment by jasonkhadka** [comment]
* Either train_apply gets arg like `with_postprocess=True`
* Or there is a name for `preprocess+forward` like `model.preprocess_with_forward`
