### ISSUE TITLE
use pipdeptree for generating requirements file 

### ISSUE THREAD

**Issue by wuhu** [lf1-io/padl#289]
## Description

Currently, the versions.txt contains package names, not pip names. It would be nice if we could generate a full requirements.txt.
This appears to be very hard using pip or python built in features alone. I stumbled upon the package pipdeptree, which looks like it could be useful for that task.

## Solution

Investigate if pipdeptree helps, if so modify `dumptools.packagefinder` such that it generates pip names.

## Alternatives

Keep it the way it is.

**Comment by sjrl** [comment]
I think it's worth taking a look at `pipdeptree` to see if it helps. It seems to have a decent user base according to pypi stats and looks to have stable versions.

**Comment by wuhu** [comment]
actually pipdeptree isn't needed: #425
