### ISSUE TITLE
Grouping not kept in `pd_preprocess`, `pd_forward` and `pd_postprocess`

### ISSUE THREAD

**Issue by eramdiaz** [lf1-io/padl#304]
When we have a Transform `g` compounded by several elements and any of them is grouped, this grouping is not respected in `g.pd_preprocess` `g.pd_forward`, `g.pd_postprocess`. For example,

Let `t`  and `g` be:
```
linear = transform(torch.nn.Linear)(8, 4)
t = ((to_tensor >> padl.Batchify() >>  linear)
     + (to_tensor >> padl.Batchify() >> linear)
) - 'name' 
g = t + padl.Identity()
```
`t` is:
``` 
Rollout - "name":

   ├─▶ 0: to_tensor >> Batchify(dim=0) >> <anonymous Linear>
   │ +  
   └─▶ 1: to_tensor >> Batchify(dim=0) >> <anonymous Linear>
```
`g` is:
```
Rollout:

   ├─▶ 0: group([..>>..] + [..>>..])
   │ +  
   └─▶ 1: padl.Identity()
```
And `g.pd_preprocess` and `g.pd_forward` are, respectively:
```
Rollout:

   ├─▶ 0: to_tensor >> Batchify(dim=0)
   │ +  
   ├─▶ 1: to_tensor >> Batchify(dim=0)
   │ +  
   └─▶ 2: padl.Identity()
```
,
```
Parallel:

   ││└─▶ 0: Linear(in_features=8, out_features=4)
   ││  /  
   │└──▶ 1: Linear(in_features=8, out_features=4)
   │   /  
   └───▶ 2: padl.Identity()
```
@sjrl and me have been checking this. Maybe it would be more consistent if the grouping were kept on the `pd_forward` and `pd_preprocess`, so they would be, respectively, something like
```
Rollout:

   ├─▶ 0: group(...)
   │ +  
   ├─▶ 1: padl.Identity()
```
and
```
Parallel:

   │└─▶ 0: group(...)
   │  /  
   └──▶ 1: padl.Identity()
```

Update: this also happens in Rollouts of Parallels and viceversa, for example in
```
t = ((to_tensor >> batch >> linear) / (to_tensor >> batch >> linear)
     + (to_tensor >> batch) / (to_tensor >> batch)
)
```
.
where `t.pd_preprocess` and `t._pd_forward` are, respectively,
```
Rollout:

   ├─▶ 0: [..>>..] / [..>>..]
   │ +  
   └─▶ 1: [..>>..] / [..>>..]
```
and 
```
Parallel:

   ││└─▶ 0: Linear(in_features=8, out_features=4)
   ││  /  
   │└──▶ 1: Linear(in_features=8, out_features=4)
   │   /  
   └───▶ 2: padl.Identity()
```
.

**Comment by wuhu** [comment]
Agree, I think it can be fixed by making grouped Pipelines automatically group their preprocess forward and postprocess.

**Comment by eramdiaz** [comment]
I reopen this issue because in our fix we missed the case for the Composes. When we have a `Pipeline` `g` which includes a `Compose` whose `pd_group` is `True` (mainly the case for this is because it has a name), this grouping is not respected in `g.pd_preprocess`, `g.pd_forward` and `g.pd_postprocess`.

For example, if we define `forward_step` as 
```
forward_step = (linear >> linear) - 'forward_step_1' 
```
`forward_step` is
```
Compose - "forward_step_1":

      │
      ▼ input
   0: Linear(in_features=8, out_features=4)
      │
      ▼ input
   1: Linear(in_features=8, out_features=4)
```

And let `g` be:
```
g = to_tensor >> batch >> forward_step >> linear 
```
Then,  `g` is:
```
Compose - "g":

      │
      ▼ x
   0: to_tensor                            
      │
      ▼ args
   1: Batchify(dim=0)                      
      │
      ▼ args
   2: Linear(in_features=8, out_features=4) >> Linear(in_features=8, out_features=4)
      │
      ▼ input
   3: Linear(in_features=8, out_features=4)

```
And we get that `g.pd_forward` is:
```
Compose:

      │
      ▼ input
   0: Linear(in_features=8, out_features=4)
      │
      ▼ input
   1: Linear(in_features=8, out_features=4)
      │
      ▼ input
   2: Linear(in_features=8, out_features=4)
```

Maybe it would make more sense and would be consistent to the previous fix if we kept the grouping of `forward_step` on `g.pd_forward`, so `g.pd_forward` would be something like
```
Compose:

      │
      ▼ input
   0: Linear(in_features=8, out_features=4) >> Linear(in_features=8, out_features=4)
      │
      ▼ input
   1: Linear(in_features=8, out_features=4)
```
