### ISSUE TITLE
Adding versions to our documentation

### ISSUE THREAD

**Issue by sjrl** [lf1-io/padl#310]
## 📜 Documentation

I think we should consider having versioned documentation, similar to other packages like Pytorch https://pytorch.org/docs/stable/index.html. Right now it's not clear what version of our code that our documentation is linked to (I believe main currently).

**Comment by sjrl** [comment]
Another potentially useful tutorial: https://tech.michaelaltfield.net/2020/07/23/sphinx-rtd-github-pages-2/

**Comment by wuhu** [comment]
Plan for now:
- For each release, copy the docs folder.
- Somehow set up github pages such that one can see the different versions.
- Put the links to the different versions on a page in the docs.
