### ISSUE TITLE
remove tqdm dependency

### ISSUE THREAD

**Issue by wuhu** [lf1-io/padl#316]
## 🛰️ Feature

Currently we only use `tqdm` in `_pd_itercall` when `verbose=True`. This isn't really necessary as instead of

```python
for batch in model.eval_transform(l, verbose=True):
    ...
```
one can do

```python
for batch in tqdm(model.eval_transform(l)):
    ...
```

which in my mind is a bit nicer because 
- more explicit
- no need for extra requirement
- we leave the choice of progress bar to the user

(we might need to do a little change to _pd_itercall in order to make it get the length properly).

**Comment by sjrl** [comment]
I agree this makes it more explicit. Additionally, users may want to toggle between `from tqdm.notebook import tqdm` and `from tqdm import tqdm` depending on what environment they are in.
