### ISSUE TITLE
Add notebooks to Google Colab

### ISSUE THREAD

**Issue by sjrl** [lf1-io/padl#324]
## Description

Add jupyter notebooks in `notebooks` to google colab for easy sharing. Create a link to the google colab in the README. 

## Solution

- [x] Add the notebooks to the shared google drive
- [x] set up correct permissions

## Alternative
Use this kind of link https://colab.research.google.com/github/lf1-io/padl/ which can be made into a badge as well
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lf1-io/padl/)
```python
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lf1-io/padl/)
```
to directly prompt users to open our notebooks into their own google colab environment. Explained here: https://github.com/weiji14/deepbedmap/issues/61
- [x] Make sure notebooks can be directly run (including installing all dependencies)
- [ ] Update the pypi artifact to include a version of PADL that supports python 3.7
- [x] Add Colab badge to README

**Comment by sjrl** [comment]
- [ ] Update the pypi artifact to include a version of PADL that supports python 3.7

**Comment by wuhu** [comment]
decision: use direct github-colab links instead of drive

**Comment by jasonkhadka** [comment]
@sjrl  Regarding batch, `Open in colab` batch is not quite clear. I think it is better if there is section under `Getting Started` with direct links to the notebooks.

**Comment by sjrl** [comment]
I have done both in PR #329 that you opened.

**Comment by jasonkhadka** [comment]
Yup updated the links directly under getting started on https://github.com/lf1-io/padl/pull/329
i removed your 
`Try out our example notebooks here: https://colab.research.google.com/github/lf1-io/padl/` 

with the direct list of notebooks under `Getting Started`:

### Try out PADL in Colab notebooks

1. [MNIST](https://colab.research.google.com/github/lf1-io/padl/blob/main/notebooks/01_MNIST_using_padl.ipynb#scrollTo=bd560eb8)
2. [Simple NLP example](https://colab.research.google.com/github/lf1-io/padl/blob/main/notebooks/02_nlp_example.ipynb)
3. [Sentiment Analysis - NLP](https://colab.research.google.com/github/lf1-io/padl/blob/main/notebooks/03_Sentiment_Analysis_with_padl.ipynb)

**Comment by jasonkhadka** [comment]
Issues on GoogleColab to track progress on python update:
Upgrade Ubuntu: https://github.com/googlecolab/colabtools/issues/1880
Upgrade Python: https://github.com/googlecolab/colabtools/issues/2165
