### ISSUE TITLE
Support full import statements

### ISSUE THREAD

**Issue by blythed** [lf1-io/padl#362]
Things like this aren't supported:

```
import sheen.models.Discriminator
import scipy.io.wavfile.read
```

Currently we are forced to write:

```
from sheen.models import Discriminator
from scipy.io.wavfile import read
```

**Comment by DipayanP007** [comment]
Hi @blythed so you can me toh change these to imports to the form `import package_name.module` ??

**Comment by blythed** [comment]
@DipayanP007 no currently `from package.module import my_function` _is_ supported. However `import package.module.my_function` _is not_ supported. I believe @wuhu has a fix in review.

**Comment by wuhu** [comment]
@blythed not yet, working on it.
